#说明：该文件用于部署mongodb副本集,副本集中包含两个节点;
#数据位置：windows下只能将数据库的数据交由docker卷管理;linux下建议将数据交由主机系统管理以提高io性能
#主机地址：在服务service-mongo_0中须配置副本集的所有机器ip与端口
#镜像：多机器的副本集需要为每个容器配置安全密钥文件,安全密钥文件需要有权限限制,无法通过挂载主机目录实现;故容器的镜像自编译的镜像
#连接url示例：mongodb://root:123456@127.0.0.1:17018,127.0.0.1:17017/?authSource=admin&replicaSet=rs0&readPreference=secondaryPreferred
version: "3.8"
services:
  # mongoDB
  service-mongo_0:
    # image: mongotest
    build: ./build
    container_name: mongo_0
    networks:
      - net_default
    volumes:
      # - ./mongo/r0/data/db/:/data/db
      - vol_mongo_r0:/data/db
      - ./mongo/r0/data/log/:/var/log/mongodb/
      - ./mongo/r0/data/configdb/:/data/configdb/
      - ./mongo/r0/run.sh:/home/run.sh
    env_file:
      - .env
    environment:
      # 以下的HOST可以是ip:port，也可以是hostName:port;为后者时必须保证你域名能够正常解析(spring boot连接副本集时会拿到这里提供的副本集主机名,你要保证spring boot能够解析出来)
      # 本地部署将以下ip地址改为本机在交换机下的ip;
      MONGO_DB_HOST_0: 192.168.1.115:17017
      MONGO_DB_HOST_1: 192.168.1.115:17018
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PWD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}
    ports:
      - "17017:27017"
    # 在这里初始化replicat set
    healthcheck:
      test: ["CMD", "bash", "/home/run.sh"]
      interval: 10s
      start_period: 30s
    command: ["--keyFile", "/home/keys/replicaKey","--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all"]
    restart: always

  # mongoDB 副本
  service-mongo_1:
    # image: mongotest
    build: ./build
    container_name: mongo_1
    networks:
      - net_default
    volumes:
      # - ./mongo/r1/data/db/:/data/db
      - vol_mongo_r1:/data/db
      - ./mongo/r1/data/log/:/var/log/mongodb/
      - ./mongo/r1/data/configdb/:/data/configdb/
    env_file:
      - .env
    environment:
      # 容器名
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USR}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PWD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_DATABASE}
      MONGO_REPLICA_SET_NAME: ${MONGO_REPLICA_SET_NAME}
    ports:
      - "17018:27017"
    # 在这里初始化replicat set
    command: ["--keyFile", "/home/keys/replicaKey","--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all"]
    restart: always

volumes: 
  vol_mongo_r0:
  vol_mongo_r1:

# 创建网络/指定网络
networks:
  # 默认网络,默认driver为bridge
  net_default: